"use strict";
/* 线代难点小讲义：中英两套，按语言取。
 *
 * 内容放在这里（会打包进静态预览版）；样式见 index.html 的 .notes-body / .note-*。
 * blocks 里每一项：字符串 = 段落；{h} 小标题；{ul} 项目符号；{formula} 公式块；
 * {tip} 提示块。内容是自己写的静态文案，直接当 HTML 用（所以 < 写成 &lt;）。
 *
 * 两种语言用同一个 id，切换语言时按 id 重画即可。
 */
window.LA_NOTES = {
  zh: [
    {
      id: "cofactor",
      title: "代数余子式到底在干什么",
      tag: "行列式",
      lead: "一句话：把 n 阶行列式「拆」成 n 个 (n−1) 阶行列式的带符号和；还不够小就接着拆，直到只剩 1 阶。",
      blocks: [
        { h: "先记住展开公式" },
        { formula: "det(A) = Σⱼ (−1)^(i+j) · a(i,j) · M(i,j)　（i 是任选的一行）" },
        "读法：<b>固定某一行 i</b>，把这行的每个元素 a(i,j) 乘上它对应的余子式 M(i,j)，再乘符号 (−1)^(i+j)，最后全部加起来。",
        { h: "三个容易混的概念" },
        { ul: [
          "<b>余子式 M(i,j)</b>：把第 i 行和第 j 列<b>整条划掉</b>（划一个十字），剩下的小矩阵，取它的行列式。",
          "<b>代数余子式</b>：就是 (−1)^(i+j) · M(i,j)，比余子式多一个符号。",
          "<b>符号只看位置</b>：只看 (i,j)，和你划掉的那个数本身是正是负完全无关。",
        ] },
        { h: "符号怎么快速记" },
        "从左上角 (1,1) 开始是 +，然后像棋盘一样交错：+ − + / − + − / + − +。等价说法：i+j 是偶数取 +，是奇数取 −。",
        { h: "为什么可以「任选一行」" },
        "因为行列式对自己的每一行都是<b>线性</b>的（把某一行拆成两项之和，行列式就等于两个行列式之和），而且<b>交换两行会变号</b>。把第 i 行拆成 n 个「只有第 j 个位置非零」的行，剩下的那个行列式正好就是 M(i,j)，换行带来的符号正好是 (−1)^(i+j)。所以沿任何一行、任何一列展开，结果都一样 —— 挑最好算的那条就行。",
        { h: "最容易卡的 4 个点" },
        { ul: [
          "忘了要<b>递归</b>：展开出来的每一项还是一个低一阶的行列式，得接着展开，不是一步出结果。",
          "划错范围：是「第 i 行<b>和</b>第 j 列」都划掉（十字），不是只划一个。",
          "把 M(i,j)（余子式）和「代数余子式」当成一回事（差一个 (−1)^(i+j)）。",
          "符号看错：只看位置，不看数字的正负。",
        ] },
        { h: "手算技巧" },
        "<b>永远挑 0 最多的那一行或那一列展开</b>：0 乘任何余子式都是 0，那一项可以直接跳过，能省掉一大半工作。",
        { tip: "在本页试一下：操作选「行列式 det(A)」，把旁边的「det 算法」切成「代数余子式展开」。每一步都会跟着一张<strong>这一步的余子式</strong>，对着上面的公式慢慢走一遍就通了。" },
      ],
    },
    {
      id: "row-reduction",
      title: "为什么行列式能用行变换来算",
      tag: "行列式",
      lead: "因为行列式对三种初等行变换的反应非常规则；把它化成三角阵，答案就是对角线相乘。",
      blocks: [
        { h: "三种行变换对 det 的影响" },
        { ul: [
          "交换两行 → 行列式<b>变号</b>",
          "某一行乘以常数 k → 行列式<b>也乘 k</b>",
          "某一行加上另一行的倍数 → 行列式<b>不变</b>",
        ] },
        { h: "化到三角阵就结束了" },
        "上三角（或下三角）矩阵的行列式 = 对角线元素相乘。因为按第一行（或第一列）展开时只有一项非零，一路递归下去就只剩主对角线。",
        { formula: "det(A) = (−1)^s · ∏ᵢ u(i,i)　（s = 交换行的次数）" },
        { h: "和 LU 分解的关系" },
        "消元得到的 U 就是上三角，L 是单位下三角（对角线全是 1，所以 det(L) = 1），P 记录了换行。由 PA = LU 得 det(P)·det(A) = det(L)·det(U)，而 det(P) = (−1)^s，于是 det(A) = (−1)^s · ∏u(i,i)。本页的「行变换法」走的就是这条路线。",
        { h: "为什么大矩阵必须用行变换" },
        "代数余子式展开要算 n! 项（3 阶 6 项、6 阶 720 项、10 阶 360 多万项）；行变换只需要大约 n³ 次运算。所以：<b>小矩阵用代数余子式理解原理，大矩阵用行变换去算</b>。两种算法的结果必然相同。",
        { tip: "在本页试一下：同一个矩阵先选「行变换法」算一次，再切「代数余子式展开」算一次。数值必然一样，但步骤风格完全不同。" },
      ],
    },
    {
      id: "matmul",
      title: "矩阵乘法为什么这么怪",
      tag: "矩阵运算",
      lead: "「行乘列再相加」不是随便定的，它对应的含义是：先做一个变换，再做另一个变换。",
      blocks: [
        { h: "两种等价的读法" },
        { ul: [
          "<b>行 × 列</b>：(A·B)(i,j) = A 的第 i 行与 B 的第 j 列做点积。",
          "<b>列的线性组合</b>：A·B 的第 j 列 = A 乘以 B 的第 j 列 —— B 的每一列在告诉你「把 A 的各列怎么混起来」。",
        ] },
        { h: "所以 AB 一般不等于 BA" },
        "矩阵代表变换。A·B 的意思是<b>先做 B、再做 A</b>；顺序一换结果就不同（先旋转再拉伸 ≠ 先拉伸再旋转）。",
        { h: "维度规则" },
        "只有 (m×k)·(k×n) 才合法：中间那个 k 必须对上，结果维度是 m×n。",
        { tip: "在本页试一下：A、B 都填好，操作选「矩阵乘法 A×B」算一次；再交换成 B×A 算一次，对比结果。" },
      ],
    },
    {
      id: "singular",
      title: "det = 0 为什么就没有逆",
      tag: "可逆性",
      lead: "因为行列式是「体积缩放因子」。为 0 意味着空间被压扁了，压扁之后信息丢了，回不去。",
      blocks: [
        { h: "几何图像" },
        "2×2 矩阵把单位正方形变成一个平行四边形，|det| 就是它的面积（3×3 对应体积）。det = 0 → 面积/体积变成 0 → 平面被压成一条线甚至一个点：降维了。此时两个不同的输入可能被映射到同一个输出，这个映射就没办法反推。",
        { h: "四句话说的是一件事" },
        { ul: [
          "A 不可逆",
          "det(A) = 0",
          "A 的行（或列）线性相关",
          "rank(A) &lt; n（存在非零的零空间向量）",
        ] },
        "这四个说法互相等价，看到其中一个就能推出另外三个。",
        { tip: "在本页试一下：填一个两行成比例的矩阵（比如第 2 行 = 2 × 第 1 行），先求逆看提示，再算它的行列式和秩。" },
      ],
    },
    {
      id: "rank",
      title: "秩到底在说什么",
      tag: "秩",
      lead: "秩 = 这个矩阵里「真正独立的信息」有几条。",
      blocks: [
        { h: "三个等价的说法" },
        { ul: [
          "线性无关的行的最大个数（也等于线性无关列的最大个数）",
          "化成 REF 之后<b>主元的个数</b>",
          "它把空间映射到的「像空间」的维数 —— 输出被压到了几维",
        ] },
        { h: "秩不足意味着什么" },
        "秩 &lt; n 说明有冗余的行（能被别人线性组合出来）。于是 A·x = 0 有非零解（零空间里的向量就是被压成 0 的那些方向），而 A·x = b 可能无解、也可能有无穷多解。",
        { tip: "在本页试一下：操作选「秩 rank(A)」和「REF 行阶梯形」各算一次 —— 数一数 REF 里的主元个数，一定等于 rank。" },
      ],
    },
    {
      id: "eigen",
      title: "特征值 / 特征向量的几何意义",
      tag: "特征值",
      lead: "Av = λv 的意思是：向量 v 在这个变换下<b>方向不变</b>，只是被拉长或压短了 λ 倍。",
      blocks: [
        { h: "为什么重要" },
        "一般向量被矩阵一乘，方向和长度都会变；特征向量是「例外」的那些方向 —— 它们揭示了变换最本质的行为：沿这些方向只是缩放。",
        { h: "特征值告诉你什么" },
        { ul: [
          "λ = 0：这个方向被压成 0 → 矩阵一定不可逆、det = 0。",
          "λ 是复数：这个方向其实被<b>旋转</b>了（比如旋转 90° 的矩阵没有实特征向量）。",
          "<b>代数重数</b>：特征多项式里这个根的次数；<b>几何重数</b>：对应的线性无关特征向量的个数。",
        ] },
        { h: "为什么有些矩阵不能对角化" },
        "当某个特征值的几何重数 &lt; 代数重数时，特征向量不够多、凑不齐一组基，就没法对角化（本页的结果里会直接标出「不可对角化」）。",
        { tip: "在本页试一下：用 [[0,-1],[1,0]] 算特征值 —— 你会看到 λ = i / −i，这就是「纯旋转」；再拿 [[2,0],[0,2]] 对比。" },
      ],
    },
    {
      id: "adjugate",
      title: "伴随矩阵与求逆公式",
      tag: "可逆性",
      lead: "把余子式矩阵转置一下得到伴随矩阵 adj(A)，它直接给出求逆公式 A⁻¹ = adj(A)/det(A)。",
      blocks: [
        { h: "从余子式矩阵到伴随矩阵" },
        "本页新增了「余子式矩阵 C &amp; 伴随矩阵 adj(A)」这个运算：C 的每个元素 C(i,j) = (−1)^(i+j)·M(i,j)；而 <b>伴随矩阵 adj(A) = Cᵀ</b>（把 C 转置）。",
        { h: "为什么它能求逆" },
        "代数上有恒等式 A · adj(A) = adj(A) · A = det(A) · I。只要 det(A) ≠ 0，两边同除以 det(A) 就得到 A⁻¹ = adj(A)/det(A)。这就是伴随求逆法。",
        { formula: "A⁻¹ = adj(A) / det(A)　（det(A) ≠ 0）" },
        { h: "它和 Gauss 求逆的关系" },
        "两者结果必然相同。但伴随法要算 n² 个余子式（每个都是 n−1 阶行列式），是 O(n·n!)；高斯消元是 O(n³)。所以：<b>伴随法用来理解原理和写公式，Gauss 法用来真算</b>。",
        { h: "三个结论打包带走" },
        { ul: [
          "det(A) = 0 ⟺ adj(A) 退化（不可逆时伴随矩阵要么全 0、要么秩 ≤ 1）",
          "逆存在 ⟺ det(A) ≠ 0 ⟺ adj(A) ≠ 0",
          "2×2 有超好记的口诀：主对角互换、副对角变号，再除以 det。",
        ] },
        { tip: "在本页试一下：填一个 2×2 或 3×3 矩阵，操作选「余子式矩阵 C &amp; 伴随矩阵 adj(A)」；再把同一个矩阵拿去「方阵求逆 A⁻¹」，对照着看 adj(A)/det 和 Gauss 逆是否一致。" },
      ],
    },
    {
      id: "orthogonal",
      title: "正交矩阵与正交变换",
      tag: "矩阵运算",
      lead: "正交矩阵就是「保长度、保角度」的变换：转置等于逆，QᵀQ = I。",
      blocks: [
        { h: "定义" },
        "方阵 Q 叫正交矩阵，当且仅当它的列（也等价于行）两两正交且都是单位向量。等价地：<b>QᵀQ = I，也就是 Qᵀ = Q⁻¹</b>。",
        { formula: "Qᵀ · Q = I　⇔　Q⁻¹ = Qᵀ" },
        { h: "几何意义：刚性运动" },
        "正交变换只做<b>旋转和反射</b>，既不拉伸也不压扁：任意向量被它一乘，长度不变（‖Qx‖ = ‖x‖），向量之间的夹角也不变。所以「正交」=「不改变内积」。",
        { h: "行列式只有 ±1" },
        "因为 det(QᵀQ) = det(I) = 1，而 det(Qᵀ) = det(Q)，所以 det(Q)² = 1 → det(Q) = 1 或 −1。det = 1 是纯旋转，det = −1 含一次反射。",
        { h: "和特征值的关系" },
        "正交矩阵的特征值都落在单位圆上（复数），模长全是 1；实特征值只能是 ±1。旋转矩阵的复特征值就是 e^(±iθ)。",
        { tip: "在本页试一下：填一个旋转矩阵 [[cosθ,−sinθ],[sinθ,cosθ]]（把 θ 换成具体数，如 30°→√3/2 与 1/2），算它的转置和逆，验证 Qᵀ = Q⁻¹；再算特征值，会看到 e^(±iθ)。" },
      ],
    },
  ],

  en: [
    {
      id: "cofactor",
      title: "What cofactors are actually doing",
      tag: "Determinant",
      lead: "In one line: it splits an n×n determinant into a signed sum of n smaller (n−1)×(n−1) determinants — and keeps splitting until only 1×1 is left.",
      blocks: [
        { h: "The expansion formula to memorise" },
        { formula: "det(A) = Σⱼ (−1)^(i+j) · a(i,j) · M(i,j)　(i is whichever row you pick)" },
        "How to read it: <b>fix one row i</b>, multiply each entry a(i,j) by its minor M(i,j) and by the sign (−1)^(i+j), then add everything up.",
        { h: "Three terms that are easy to mix up" },
        { ul: [
          "<b>Minor M(i,j)</b>: cross out <b>the whole</b> i-th row and j-th column (a cross shape), then take the determinant of what is left.",
          "<b>Cofactor</b>: that is (−1)^(i+j) · M(i,j) — the minor plus a sign.",
          "<b>The sign depends only on position</b>: only (i,j) matters, not whether the entry you crossed out was positive or negative.",
        ] },
        { h: "A quick way to remember the signs" },
        "Start at the top-left (1,1) with + and alternate like a chessboard: + − + / − + − / + − +. Equivalently: + when i+j is even, − when it is odd.",
        { h: "Why you may pick any row" },
        "Because the determinant is <b>linear</b> in each of its rows (split one row into a sum of two and the determinant splits accordingly), and <b>swapping two rows flips the sign</b>. Split row i into n rows that are zero everywhere except position j, and the remaining determinant is exactly M(i,j); the sign picked up from moving rows is exactly (−1)^(i+j). So expanding along any row or any column gives the same answer — just pick the easiest one.",
        { h: "Four places people get stuck" },
        { ul: [
          "Forgetting it is <b>recursive</b>: every term is still a determinant one size smaller — you keep expanding, it is not a single step.",
          "Crossing out the wrong things: it is the i-th row <b>and</b> the j-th column (a cross), not just one of them.",
          "Treating the minor M(i,j) and the cofactor as the same thing (they differ by (−1)^(i+j)).",
          "Getting the sign wrong: look at the position, not at the sign of the number.",
        ] },
        { h: "A hand-calculation trick" },
        "<b>Always expand along the row or column with the most zeros</b>: 0 times any minor is 0, so you can skip that term entirely — it often saves more than half the work.",
        { tip: "Try it here: pick \"Determinant det(A)\" and switch \"det method\" to \"Cofactor expansion\". Every step comes with <strong>the minor for that step</strong> — walk through it next to the formula above and it clicks." },
      ],
    },
    {
      id: "row-reduction",
      title: "Why row operations can compute a determinant",
      tag: "Determinant",
      lead: "Because the determinant reacts to the three elementary row operations in a perfectly predictable way: reduce to triangular form and the answer is just the product of the diagonal.",
      blocks: [
        { h: "What the three row operations do to det" },
        { ul: [
          "Swap two rows → the determinant <b>changes sign</b>",
          "Multiply a row by k → the determinant <b>is also multiplied by k</b>",
          "Add a multiple of one row to another → the determinant <b>does not change</b>",
        ] },
        { h: "Once it is triangular you are done" },
        "The determinant of an upper (or lower) triangular matrix is the product of its diagonal entries. Expanding along the first row (or column) leaves only one non-zero term, and recursing leaves just the main diagonal.",
        { formula: "det(A) = (−1)^s · ∏ᵢ u(i,i)　(s = number of row swaps)" },
        { h: "The link with LU decomposition" },
        "Elimination produces U (upper triangular) and L (unit lower triangular — every diagonal entry is 1, so det(L) = 1), while P records the row swaps. From PA = LU we get det(P)·det(A) = det(L)·det(U), with det(P) = (−1)^s, so det(A) = (−1)^s · ∏u(i,i). The \"Row reduction\" method on this page is exactly that route.",
        { h: "Why bigger matrices have to use row operations" },
        "Cofactor expansion needs n! terms (6 for 3×3, 720 for 6×6, over 3.6 million for 10×10); row reduction needs roughly n³ operations. So: <b>use cofactors to understand the idea, use row operations to actually compute</b>. The two methods must agree.",
        { tip: "Try it here: run the same matrix with \"Row reduction (recommended)\", then switch to \"Cofactor expansion\". The value is identical — only the style of the steps differs." },
      ],
    },
    {
      id: "matmul",
      title: "Why matrix multiplication looks so weird",
      tag: "Matrix ops",
      lead: "\"Row times column, then add\" is not arbitrary — it means: apply one transformation, then the other.",
      blocks: [
        { h: "Two equivalent readings" },
        { ul: [
          "<b>Row × column</b>: (A·B)(i,j) is the dot product of row i of A with column j of B.",
          "<b>A combination of columns</b>: column j of A·B equals A times column j of B — each column of B tells you <i>how to mix the columns of A</i>.",
        ] },
        { h: "So AB usually is not BA" },
        "A matrix is a transformation, and A·B means <b>do B first, then A</b>. Swap the order and the result changes (rotate then stretch ≠ stretch then rotate).",
        { h: "The dimension rule" },
        "Only (m×k)·(k×n) is valid: the inner k must match, and the result is m×n.",
        { tip: "Try it here: fill in both A and B, run \"Matrix product A×B\", then swap the operands and run B×A. Compare the two." },
      ],
    },
    {
      id: "singular",
      title: "Why det = 0 means there is no inverse",
      tag: "Invertibility",
      lead: "Because the determinant is the \"volume scale factor\". Zero means space got squashed flat — and once squashed, information is lost and you cannot go back.",
      blocks: [
        { h: "The geometric picture" },
        "A 2×2 matrix turns the unit square into a parallelogram, and |det| is its area (volume for 3×3). det = 0 → the area/volume is 0 → the plane collapsed onto a line or even a point: a dimension was lost. Two different inputs can then land on the same output, and such a map cannot be reversed.",
        { h: "Four sentences that all say one thing" },
        { ul: [
          "A is not invertible",
          "det(A) = 0",
          "The rows (or columns) of A are linearly dependent",
          "rank(A) &lt; n (there is a non-zero null-space vector)",
        ] },
        "These four are equivalent — seeing any one of them implies the other three.",
        { tip: "Try it here: fill in a matrix whose rows are proportional (say row 2 = 2 × row 1), try \"Inverse A⁻¹\" and read the message, then compute its determinant and rank." },
      ],
    },
    {
      id: "rank",
      title: "What rank is really saying",
      tag: "Rank",
      lead: "Rank = how many genuinely independent pieces of information the matrix holds.",
      blocks: [
        { h: "Three equivalent descriptions" },
        { ul: [
          "The largest number of linearly independent rows (which equals the largest number of independent columns)",
          "The number of <b>pivots</b> once you reach REF",
          "The dimension of the image — how many dimensions the output got mapped into",
        ] },
        { h: "What a rank deficit means" },
        "Rank &lt; n means there are redundant rows (some row is a linear combination of the others). Then A·x = 0 has non-zero solutions (the null space is exactly the set of directions squashed to 0), and A·x = b may have no solution or infinitely many.",
        { tip: "Try it here: run \"Rank rank(A)\" and \"REF (row echelon form)\" on the same matrix — count the pivots in the REF and it always equals the rank." },
      ],
    },
    {
      id: "eigen",
      title: "The geometry of eigenvalues and eigenvectors",
      tag: "Eigenvalues",
      lead: "Av = λv means: under this transformation the vector v <b>keeps its direction</b> and is only stretched or squashed by a factor λ.",
      blocks: [
        { h: "Why it matters" },
        "A general vector changes both direction and length when a matrix acts on it. Eigenvectors are the <i>exceptional</i> directions — they reveal what the transformation really does: along those directions it is pure scaling.",
        { h: "What the eigenvalues tell you" },
        { ul: [
          "λ = 0: that direction is squashed to 0 → the matrix is definitely not invertible and det = 0.",
          "λ is complex: that direction is actually being <b>rotated</b> (a 90° rotation matrix has no real eigenvectors).",
          "<b>Algebraic multiplicity</b>: how many times the root appears in the characteristic polynomial; <b>geometric multiplicity</b>: how many independent eigenvectors belong to it.",
        ] },
        { h: "Why some matrices cannot be diagonalised" },
        "When the geometric multiplicity of some eigenvalue is &lt; its algebraic multiplicity there are not enough eigenvectors to form a basis, so diagonalisation is impossible (this page flags it directly as \"not diagonalisable\").",
        { tip: "Try it here: compute the eigenvalues of [[0,-1],[1,0]] — you will get λ = i / −i, which is a pure rotation; then contrast it with [[2,0],[0,2]]." },
      ],
    },
    {
      id: "adjugate",
      title: "The adjugate and the inverse formula",
      tag: "Invertibility",
      lead: "Transpose the cofactor matrix and you get the adjugate adj(A), which hands you the inverse formula A⁻¹ = adj(A)/det(A) directly.",
      blocks: [
        { h: "From cofactor matrix to adjugate" },
        "This page has a \"Cofactor matrix C &amp; adjugate adj(A)\" operation: every entry of C is C(i,j) = (−1)^(i+j)·M(i,j), and the <b>adjugate is adj(A) = Cᵀ</b> (C transposed).",
        { h: "Why that gives the inverse" },
        "There is an identity A · adj(A) = adj(A) · A = det(A) · I. As long as det(A) ≠ 0, divide both sides by det(A) and you get A⁻¹ = adj(A)/det(A). That is the adjugate method for inverses.",
        { formula: "A⁻¹ = adj(A) / det(A)　(det(A) ≠ 0)" },
        { h: "How it relates to Gauss–Jordan" },
        "Both give the same answer. But the adjugate route needs n² cofactors, each an (n−1)×(n−1) determinant — that is O(n·n!), while Gaussian elimination is O(n³). So: <b>the adjugate is for understanding and for formulas, Gauss is for actually computing</b>.",
        { h: "Three takeaways" },
        { ul: [
          "det(A) = 0 ⟺ adj(A) is degenerate (when A is singular the adjugate is either all zeros or has rank ≤ 1)",
          "An inverse exists ⟺ det(A) ≠ 0 ⟺ adj(A) ≠ 0",
          "For 2×2 there is a classic shortcut: swap the main diagonal, flip the signs on the other diagonal, divide by det.",
        ] },
        { tip: "Try it here: enter a 2×2 or 3×3 matrix and pick \"Cofactor matrix C &amp; adjugate adj(A)\"; then run \"Inverse A⁻¹\" on the same matrix and check that adj(A)/det matches the Gauss–Jordan inverse." },
      ],
    },
    {
      id: "orthogonal",
      title: "Orthogonal matrices and orthogonal transformations",
      tag: "Matrix ops",
      lead: "An orthogonal matrix is a transformation that <b>preserves lengths and angles</b>: its transpose is its inverse, QᵀQ = I.",
      blocks: [
        { h: "Definition" },
        "A square matrix Q is orthogonal exactly when its columns (equivalently, its rows) are mutually orthogonal unit vectors. Equivalently: <b>QᵀQ = I, i.e. Qᵀ = Q⁻¹</b>.",
        { formula: "Qᵀ · Q = I　⇔　Q⁻¹ = Qᵀ" },
        { h: "Geometric meaning: rigid motions" },
        "Orthogonal transformations only <b>rotate and reflect</b> — they never stretch or squash: multiplying any vector by one leaves its length unchanged (‖Qx‖ = ‖x‖) and leaves the angles between vectors unchanged. So \"orthogonal\" means \"preserves the inner product\".",
        { h: "The determinant is only ever ±1" },
        "Since det(QᵀQ) = det(I) = 1 and det(Qᵀ) = det(Q), we get det(Q)² = 1, so det(Q) = 1 or −1. det = 1 is a pure rotation; det = −1 includes a reflection.",
        { h: "The link with eigenvalues" },
        "All eigenvalues of an orthogonal matrix lie on the unit circle (in the complex plane) and have modulus 1; real eigenvalues can only be ±1. For a rotation matrix the complex eigenvalues are e^(±iθ).",
        { tip: "Try it here: enter the rotation matrix [[cosθ,−sinθ],[sinθ,cosθ]] with a concrete θ (say 30° → √3/2 and 1/2), compute its transpose and its inverse, and check that Qᵀ = Q⁻¹; then compute the eigenvalues and you will see e^(±iθ)." },
      ],
    },
  ],
};
